### ISSUE TITLE
Rename the `print` type and function to `log`

### ISSUE THREAD

**Issue by FarmerSez** [FarmerSez/tracy#10]
This is a really minor change.
I want the parts that are related to printing to stderr / another handler to be called `log` and not `print`.
e.g:

`typedef void (*TRC_err_print_callback)(char const * fmt, va_list vargs);` should be changed to `TRC_err_log_callback`, etc.

**Comment by sangeet259** [comment]
Do you want them to be just called 'log' ?, i.e. you still want them to be printed to stderr?

**Comment by FarmerSez** [comment]
I want the function and actions to be called `log`. What they do is log the traceback, it is coincidental that it prints it to `stderr`. It could be written to a file just as much.

**Comment by FarmerSez** [comment]
Done in #12 .
