### ISSUE TITLE
Add a way to initialize tracy with a custom stack size

### ISSUE THREAD

**Issue by FarmerSez** [FarmerSez/tracy#4]

**Comment by platipo** [comment]
Could you provide more details?

**Comment by FarmerSez** [comment]
The stack size is initializes to a constant now. I'd like it to be a parameter at initialization. Something like
`TRC_err TRC_init(uint stack_size);`

**Comment by platipo** [comment]
I was thinking about usign `getrlimit` to get current stack size and pad it with `alloca`. But I don't see how you would manage it. Can you work it out?

**Comment by FarmerSez** [comment]
I'm trying to make `tracy` cross compatible to windows, so using `getrlimit` won't necessarily work. Perhaps just allocate the size given as a parameter?

I don't mean that `tracy`'s stack limit should be the size of the actual process stack. In my case, I used it on embedded software, so I wanted to consume as less memory as possible. I think that the user could do `TRC_init(getrlimit())` (conceptually) if he wishes to.

**Comment by platipo** [comment]
Anyway if you want custom stack allocation my idea is:
```C
#ifdef __linux__
 #include <allloca.h>
#elif _WIN32
 #include <malloc.h>
 #define alloca _alloca
#endif

static void *stack;

TRC_err TRC_init(uint stack_size) {
    stack = alloca(stack_size - lim.rlim_cur);
}
```

**Comment by meircif** [comment]
How about this:

instead of
```c
typedef struct {
  stack_buff buffer[MAX_STACK_SIZE];
} error_stack;

static __thread error_stack local_stack;
```
there will be
```c
extern __thread stack_buff local_stack[];
#define TRC_ALLOCATE_STACK(stack_size) __thread stack_buff local_stack[stack_size]
```
and then the user needs to add this line in the global scope of one of his source files
```c
TRC_ALLOCATE_STACK(1024);
```

**Comment by FarmerSez** [comment]
Me gusta @meircif. I think it would also be nice if there will be an error in linkage other than "undefined reference". Is that possible?

**Comment by FarmerSez** [comment]
Well, I think I'm okay with that solution. Only make sure that:
1. The buffer name starts with `TRC_`
2. Update the README
3. Add a part to the README below it that has an example error copied from a failed linkage (`ld: undefined reference to TRC_stack.....`), so it may be found if searched.

**Comment by meircif** [comment]
#13
